-- AlterEnum
ALTER TYPE "ModuleType" ADD VALUE 'IELTS_GENERAL';
ALTER TYPE "ModuleType" ADD VALUE 'IELTS_ACADEMIC';
ALTER TYPE "ModuleType" ADD VALUE 'COMBINED';

-- AlterEnum
ALTER TYPE "QuestionType" ADD VALUE 'MAP_LABELLING';
ALTER TYPE "QuestionType" ADD VALUE 'PROCESS_DIAGRAM';
ALTER TYPE "QuestionType" ADD VALUE 'YES_NO_NOT_GIVEN';
ALTER TYPE "QuestionType" ADD VALUE 'TRUE_FALSE_NOT_GIVEN';
ALTER TYPE "QuestionType" ADD VALUE 'HEADING_MATCHING';
ALTER TYPE "QuestionType" ADD VALUE 'INFORMATION_MATCHING';
ALTER TYPE "QuestionType" ADD VALUE 'FEATURES_MATCHING';
ALTER TYPE "QuestionType" ADD VALUE 'SPEAKING_TASK_1';
ALTER TYPE "QuestionType" ADD VALUE 'SPEAKING_TASK_2';
ALTER TYPE "QuestionType" ADD VALUE 'SPEAKING_TASK_3';

-- AlterTable
ALTER TABLE "Test" ADD COLUMN "isFeatured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Test" ADD COLUMN "testCategory" TEXT;

-- AlterTable
ALTER TABLE "Question" ADD COLUMN "passage" TEXT;
ALTER TABLE "Question" ADD COLUMN "cueCard" TEXT;
ALTER TABLE "Question" ADD COLUMN "speakingPrompts" JSONB;
ALTER TABLE "Question" ADD COLUMN "bandDescriptors" JSONB;
ALTER TABLE "Question" ADD COLUMN "sampleAnswer" TEXT; 